### ISSUE TITLE
Windows shows warnings for signed package

### ISSUE THREAD

**Issue by sensboston** [joepitt91/SignClickOnceApp#2]
Hi Joe,
CERTUM guys recommended me your project for "ClickOnce" signing. Unfortunately, I can't get my "ClickOnce" installation properly: Windows shows bunch of warnings about "dangerous" content etc. (but why did I pay money for CERTUM code signing certificate?).

Here is my [project link](https://github.com/sensboston/BLEConsole), [this page](https://sensboston.github.io/BLEConsole/) has a link to ClickOnce installer.

For the signing, I'm using this command:
``.\SignClickOnceApp.ps1 -VSRoot D:\Projects -SolutionName BLEConsole -ProjectName BLEConsole -SHA256CertThumbprint 5347b383606d271ed99dc0b4805492b6280b23ff -TimeStampingServer http://timestamp.comodoca.com/ -PublisherName Open Source Developer, Sergey Svinolobov``

Could you please tell me, what I'm doing wrong? Thanks a lot!

**Comment by joepitt91** [comment]
Could you elaborate on exactly what messages Windows is showing with the signed package?

Assuming it is SmartScreen throwing errors, this uses a wide range of metrics to determine whether or not to show a warning, including:
* Digital signatures,
* revocation status of certificate used to sign, 
* How many times it has seen the executable before (freshly signed EXEs will often throw SmartScreen warnings as they have never been seen before),
* Observed activity, i.e. if the EXE has been observed to carry out suspicious activity, 
* etc. 

Could you comment the output of: `.\SignClickOnceApp.ps1 -VSRoot D:\Projects -SolutionName BLEConsole -ProjectName BLEConsole -SHA256CertThumbprint 5347b383606d271ed99dc0b4805492b6280b23ff -TimeStampingServer http://time.certum.pl -PublisherName "Sergey Svinolobov" -Verbose`

This uses the timestamping server from Certum and quotes the Publisher Name as it has spaces (this does not need to match the certificate CN value).

**Comment by mujroshan** [comment]
Hi Joe, thank you for developing this useful script. I want to use this but I get an error that the SHA is thumbprint is malformed. I think I may not be using the right SHA256CertThumbprint. Could you please tell me where do I find this thumbprint after I have published my app? 

I got this SHA256CertThumbprint by going to the \publish folder: source\repos\MyApp\MyApp\publish\Application Files\MyApp_1_0_0_2  then right-clicking the MyApp.Application file and copied the long signature hash from these tags: <dsig:DigestValue>...</dsig:DigestValue>

Is this the right SHA256CertThumbprint? If not, what file has it?

Thanks in advance.

**Comment by joepitt91** [comment]
Easiest way I've found to get certificate thumbprint is to go:

1. WinKey+R
2. Type `certmgr.msc`, Click OK
3. Navigate to `Personal/Certificates`
4. Double Click the Code Signing Certificate
5. Go to the `Details` tab
6. Scroll to the bottom of the list of properties and highlight `Thumbprint`
7. Copy and Paste the thumbprint from here into the `-SHA256CertThumbprint` parameter

NOTE:  On OSes pre Windows 10 there is an invisible character at the start of the string you'll need to delete that, and all the spaces in-between the serial number 

You should end up with something like `-SHA256CertThumbprint 00112233445566778899aabbccddeeff00112233`
